// ******************************************************************
//       /\ /|       @file       DefExample.cs
//       \ V/        @brief      auto generated by RabiConfigGenerator. ./Excel/Example.xlsx
//       | "")       @author     Shadowrabbit, yingtu0401@gmail.com
//       /  |
//      /  \\        @Modified   2022-04-25 13:25:11
//    *(__\_\        @Copyright  Copyright (c)  2022, Shadowrabbit
// ******************************************************************

namespace ExampleProject.Defs
{
    public static class DefExample
    {
        public static readonly string DUnitOnChain = "UnitOnChain"; 
        public static readonly string DUnitOnDie = "UnitOnDie"; 
        public static readonly string DHeroOnHit = "HeroOnHit"; 
    }
}